name: Docker Build and Publish

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push master branch
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: lanthora/candy:latest

      - name: Set VERSION variable from tag without v prefix
        if: github.event_name == 'release'
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Build and push release version
        if: github.event_name == 'release'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: lanthora/candy:${{ env.VERSION }}
